import pathlib
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from typing import Union, Tuple


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if not(os.path.exists(data_fname)):
            raise ValueError
        if type(data_fname) == str:
            self.data_fname = pathlib.Path(data_fname)
        else:
            self.data_fname = data_fname

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data = pd.read_json(self.data_fname)

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        good_data_mask = self.data['age'].notna()
        age_values = self.data['age'][good_data_mask]
        hist_values, bin_values = np.histogram(age_values, bins = 10, range = (0, 100))
        plt.hist(age_values, bins = bin_values)
        plt.xlabel('Age')
        plt.ylabel('No. of participents')
        plt.show()
        return hist_values, bin_values
    
    def remove_rows_without_mail(self) -> pd.DataFrame:
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """
        good_data_mask = self.data['email'].str.contains('[0-9A-Za-z]+@[0-9A-Za-z]+.[A-Za-z]+')
        valid_email_data = self.data[good_data_mask]     
        new_max_index = len(valid_email_data.index)
        valid_email_data.index = np.arange(new_max_index)
        return valid_email_data

    def fill_na_with_mean(self) -> Union[pd.DataFrame, np.ndarray]:
        """
        Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student. Returns the corrected DataFrame,
        as well as the row indices of the students that their new grades
        were generated.
        """
        number_of_questions = 5 #for flexibility
        question_indices = []
        for idx in range(number_of_questions):
            question_indices.append('q' + str(idx+1))
            
        missing_idx = np.array([])
        work_data = self.data.copy()
        for question in question_indices:
            missing_answers = work_data[question].isna()
            missing_idx = np.union1d(missing_idx, missing_answers[missing_answers].index)
            mean_scores = np.nanmean(work_data[question_indices][missing_answers], axis = 1)
            work_data.loc[missing_answers, question] = mean_scores
        
        return work_data, missing_idx
        
    def correlate_gender_age(self) -> pd.DataFrame:
        """
        Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.
        Returns a DataFrame with a MultiIndex containing the gender and whether
        the subject is above 40 years of age, and the average score in each of
        the five questions.
        """
        number_of_questions = 5 #for flexibility
        question_indices = []
        for idx in range(number_of_questions):
            question_indices.append('q' + str(idx+1))
        relevant_columns = ['gender', 'age'] + question_indices
        relevant_data = self.data[relevant_columns]
        relevant_data = relevant_data.groupby(['gender', relevant_data.age >= 40])
        corr_scores = relevant_data.mean()
        return corr_scores
        


if __name__ == '__main__':
    QA = QuestionnaireAnalysis(pathlib.Path('data.json'))
    QA.read_data()
    QA.show_age_distrib()
    valid_mail_data = QA.remove_rows_without_mail()
    scores_fixed_data, fixed_indices = QA.fill_na_with_mean()
    corr_scores = QA.correlate_gender_age()
